server {
    listen {{ .interface }}:{{ .port }} default_server;

    include /etc/nginx/includes/server_params.conf;
    include /etc/nginx/includes/proxy_params.conf;

    absolute_redirect off;
    proxy_redirect / $http_x_ingress_path/;

    # Stirling PDF already knows how to live somewhere other than the root of a
    # domain: it writes its own base into every copy of index.html it serves,
    # taking the value from the servlet context path. Both lines below are
    # generated by ReactRoutingController, not by the frontend build, so they
    # arrive in exactly this shape and are the only two places the base
    # appears.
    #
    # Setting that context path to the Ingress path directly would be the
    # obvious move, and is wrong: the Supervisor strips the Ingress prefix
    # before it forwards, so the application would be listening at a path no
    # request ever arrives on. It stays at the root, and the two values are
    # rewritten on the way past instead.
    #
    # The frontend is built with a relative base, so the assets already resolve
    # against whatever <base href> says. That leaves the API, which axios sends
    # to STIRLING_PDF_API_BASE_URL.
    sub_filter_once off;
    sub_filter '<base href="/" />' '<base href="$http_x_ingress_path/" />';
    sub_filter "window.STIRLING_PDF_API_BASE_URL = '/';" 'window.STIRLING_PDF_API_BASE_URL = "$http_x_ingress_path/";';

    location / {
        allow   172.30.32.2;
        deny    all;

        proxy_pass http://backend;
    }
}
